import { Channel } from './channel';
import { User } from './user';
import { VideoFilterType } from './video';
import { ActiveClipCampaign } from './clipCampaign';

export type PlaybackEndpoint = {
  bitrate: number;
  downloadUrl: string;
  resolution: number;
  streamUrl: string;
};

export type Playback = {
  channelId: number;
  createTimeMs: number;
  duration: number;
  name: string;
  description: string;
  endpointList: PlaybackEndpoint[];
  snapshotUrl: string; // generated by system
  thumbnailUrl: string; // uploaded by user, thumbnail has higher priority than snapshot
  uuid: string;
  views: number;
  shareUrl: string;
  gameBuildId: number;
  likeTime: number;
  likes: number;
  lang: string;
  type: VideoFilterType;
  clipCampaign?: ActiveClipCampaign;
  tagUniqList: string[];
  displayType: number;
};

export type PlaybackItem = {
  channel: Channel;
  user: User;
  playback: Playback;
  stats: PlaybackStats;
};

export enum Sort {
  CREATE_TIME_ASC = -1,
  CREATE_TIME_DESC = 1
}

export type PlaybackStats = {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
};

export const defaultPlayback: Playback = {
  channelId: 0,
  createTimeMs: 0,
  duration: 0,
  name: '',
  description: '',
  endpointList: [],
  snapshotUrl: '',
  thumbnailUrl: '',
  uuid: '',
  views: 0,
  shareUrl: '',
  gameBuildId: 0,
  likeTime: 0,
  likes: 0,
  lang: 'en',
  type: VideoFilterType.VOD,
  tagUniqList: [],
  displayType: 0
};

