"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GiftStatus = exports.GiftLogTimeRange = exports.GiftLogOrderType = exports.GiftCategory = exports.GameIds = exports.StorageNamespace = exports.DLStatus = exports.DLRewardType = exports.DLClaimRequest = exports.defaultReplyComment = exports.defaultComment = exports.defaultBaseComment = exports.CommentStatus = exports.defaultClipCampaign = exports.Status = exports.ClipSort = exports.ClipCampaignRewardType = exports.FlushType = exports.EventType = exports.EventStatus = exports.EventSource = exports.ClanStatsType = exports.ClanStatsSort = exports.ClanStatsFilter = exports.ClanApplicationStatus = exports.ClanApplicationReview = exports.CashoutRecordStatus = exports.ChatCustomBannerType = exports.ChatBannerType = exports.assetsType = exports.assetsMode = exports.defaultStreamerAlertConfig = exports.StreamerAlertConfigName = exports.GiftRankingConfig = exports.FontSize = exports.CoinGiftConfig = exports.BgOpacity = exports.BannerAlertLayoutMode = exports.AlertDuration = exports.AlertBannerTab = exports.defaultSystemChatSettings = exports.SlowMode = exports.ShownSystemMessage = exports.SendMsgType = exports.Restriction = exports.MsgType = exports.ModActionType = exports.HiddenBanner = exports.DashboardMsgType = exports.BadgeCode = void 0;
exports.FFBindingResult = exports.ApiErrorCode = exports.UserGender = exports.ModerateContent = exports.BanningSource = exports.defaultTimeLimitedTask = exports.defaultDailyTask = exports.TLEStatus = exports.TLERewardType = exports.TLEQueryType = exports.TLEPrizeType = exports.TLEEventType = exports.TLEEventScope = exports.TLEClaimQueryType = exports.DailyTaskType = exports.DailyTaskStatus = exports.DailyTaskReward = exports.TabsScrollPostion = exports.ProgramLevel = exports.GroupTier = exports.defaultStreamerProgramStats = exports.StreamerProgramWithdrawType = exports.StreamerProgramRecordOffset = exports.StreamerProgramPayoutWithdrawStatus = exports.StreamerProgramPayoutStatus = exports.defaultLuckyDrawInfo = exports.FBPrivacy = exports.SentryDeviceDSN = exports.SearchType = exports.Type = exports.Reason = exports.defaultRankingCards = exports.RankingTimeScope = exports.RankingListKey = exports.defaultPlayback = exports.Sort = exports.StreamingPlatform = exports.SocialPlatform = exports.SharingPlatform = exports.SessionPlatform = exports.LoginPlatform = exports.ClientPlatform = exports.BannerPlatform = exports.NotificationType = exports.NewsTag = exports.FFLuckyDrawStatus = exports.FFLuckyDrawMode = exports.FFLuckyDrawCriteriaType = exports.defaultGifter = exports.GiftType = void 0;
exports.ChatClient = exports.RestAPI = exports.PlayerError = exports.VideoType = exports.VideoFormat = exports.VideoFilterType = exports.defaultServerConfig = exports.FileType = void 0;
var chat_1 = require("./types/chat");
Object.defineProperty(exports, "BadgeCode", { enumerable: true, get: function () { return chat_1.BadgeCode; } });
Object.defineProperty(exports, "DashboardMsgType", { enumerable: true, get: function () { return chat_1.DashboardMsgType; } });
Object.defineProperty(exports, "HiddenBanner", { enumerable: true, get: function () { return chat_1.HiddenBanner; } });
Object.defineProperty(exports, "ModActionType", { enumerable: true, get: function () { return chat_1.ModActionType; } });
Object.defineProperty(exports, "MsgType", { enumerable: true, get: function () { return chat_1.MsgType; } });
Object.defineProperty(exports, "Restriction", { enumerable: true, get: function () { return chat_1.Restriction; } });
Object.defineProperty(exports, "SendMsgType", { enumerable: true, get: function () { return chat_1.SendMsgType; } });
Object.defineProperty(exports, "ShownSystemMessage", { enumerable: true, get: function () { return chat_1.ShownSystemMessage; } });
Object.defineProperty(exports, "SlowMode", { enumerable: true, get: function () { return chat_1.SlowMode; } });
Object.defineProperty(exports, "defaultSystemChatSettings", { enumerable: true, get: function () { return chat_1.defaultSystemChatSettings; } });
var alertConfig_1 = require("./types/alertConfig");
Object.defineProperty(exports, "AlertBannerTab", { enumerable: true, get: function () { return alertConfig_1.AlertBannerTab; } });
Object.defineProperty(exports, "AlertDuration", { enumerable: true, get: function () { return alertConfig_1.AlertDuration; } });
Object.defineProperty(exports, "BannerAlertLayoutMode", { enumerable: true, get: function () { return alertConfig_1.BannerAlertLayoutMode; } });
Object.defineProperty(exports, "BgOpacity", { enumerable: true, get: function () { return alertConfig_1.BgOpacity; } });
Object.defineProperty(exports, "CoinGiftConfig", { enumerable: true, get: function () { return alertConfig_1.CoinGiftConfig; } });
Object.defineProperty(exports, "FontSize", { enumerable: true, get: function () { return alertConfig_1.FontSize; } });
Object.defineProperty(exports, "GiftRankingConfig", { enumerable: true, get: function () { return alertConfig_1.GiftRankingConfig; } });
Object.defineProperty(exports, "StreamerAlertConfigName", { enumerable: true, get: function () { return alertConfig_1.StreamerAlertConfigName; } });
Object.defineProperty(exports, "defaultStreamerAlertConfig", { enumerable: true, get: function () { return alertConfig_1.defaultStreamerAlertConfig; } });
var assets_1 = require("./types/assets");
Object.defineProperty(exports, "assetsMode", { enumerable: true, get: function () { return assets_1.assetsMode; } });
Object.defineProperty(exports, "assetsType", { enumerable: true, get: function () { return assets_1.assetsType; } });
var banner_1 = require("./types/banner");
Object.defineProperty(exports, "ChatBannerType", { enumerable: true, get: function () { return banner_1.ChatBannerType; } });
Object.defineProperty(exports, "ChatCustomBannerType", { enumerable: true, get: function () { return banner_1.ChatCustomBannerType; } });
var cashout_1 = require("./types/cashout");
Object.defineProperty(exports, "CashoutRecordStatus", { enumerable: true, get: function () { return cashout_1.CashoutRecordStatus; } });
var clan_1 = require("./types/clan");
Object.defineProperty(exports, "ClanApplicationReview", { enumerable: true, get: function () { return clan_1.ClanApplicationReview; } });
Object.defineProperty(exports, "ClanApplicationStatus", { enumerable: true, get: function () { return clan_1.ClanApplicationStatus; } });
Object.defineProperty(exports, "ClanStatsFilter", { enumerable: true, get: function () { return clan_1.ClanStatsFilter; } });
Object.defineProperty(exports, "ClanStatsSort", { enumerable: true, get: function () { return clan_1.ClanStatsSort; } });
Object.defineProperty(exports, "ClanStatsType", { enumerable: true, get: function () { return clan_1.ClanStatsType; } });
var clientEvents_1 = require("./types/clientEvents");
Object.defineProperty(exports, "EventSource", { enumerable: true, get: function () { return clientEvents_1.EventSource; } });
Object.defineProperty(exports, "EventStatus", { enumerable: true, get: function () { return clientEvents_1.EventStatus; } });
Object.defineProperty(exports, "EventType", { enumerable: true, get: function () { return clientEvents_1.EventType; } });
Object.defineProperty(exports, "FlushType", { enumerable: true, get: function () { return clientEvents_1.FlushType; } });
var clipCampaign_1 = require("./types/clipCampaign");
Object.defineProperty(exports, "ClipCampaignRewardType", { enumerable: true, get: function () { return clipCampaign_1.ClipCampaignRewardType; } });
Object.defineProperty(exports, "ClipSort", { enumerable: true, get: function () { return clipCampaign_1.ClipSort; } });
Object.defineProperty(exports, "Status", { enumerable: true, get: function () { return clipCampaign_1.Status; } });
Object.defineProperty(exports, "defaultClipCampaign", { enumerable: true, get: function () { return clipCampaign_1.defaultClipCampaign; } });
var comment_1 = require("./types/comment");
Object.defineProperty(exports, "CommentStatus", { enumerable: true, get: function () { return comment_1.CommentStatus; } });
Object.defineProperty(exports, "defaultBaseComment", { enumerable: true, get: function () { return comment_1.defaultBaseComment; } });
Object.defineProperty(exports, "defaultComment", { enumerable: true, get: function () { return comment_1.defaultComment; } });
Object.defineProperty(exports, "defaultReplyComment", { enumerable: true, get: function () { return comment_1.defaultReplyComment; } });
var dailyLogin_1 = require("./types/dailyLogin");
Object.defineProperty(exports, "DLClaimRequest", { enumerable: true, get: function () { return dailyLogin_1.DLClaimRequest; } });
Object.defineProperty(exports, "DLRewardType", { enumerable: true, get: function () { return dailyLogin_1.DLRewardType; } });
Object.defineProperty(exports, "DLStatus", { enumerable: true, get: function () { return dailyLogin_1.DLStatus; } });
var firebase_1 = require("./types/firebase");
Object.defineProperty(exports, "StorageNamespace", { enumerable: true, get: function () { return firebase_1.StorageNamespace; } });
var game_1 = require("./types/game");
Object.defineProperty(exports, "GameIds", { enumerable: true, get: function () { return game_1.GameIds; } });
var gift_1 = require("./types/gift");
Object.defineProperty(exports, "GiftCategory", { enumerable: true, get: function () { return gift_1.GiftCategory; } });
Object.defineProperty(exports, "GiftLogOrderType", { enumerable: true, get: function () { return gift_1.GiftLogOrderType; } });
Object.defineProperty(exports, "GiftLogTimeRange", { enumerable: true, get: function () { return gift_1.GiftLogTimeRange; } });
Object.defineProperty(exports, "GiftStatus", { enumerable: true, get: function () { return gift_1.GiftStatus; } });
Object.defineProperty(exports, "GiftType", { enumerable: true, get: function () { return gift_1.GiftType; } });
Object.defineProperty(exports, "defaultGifter", { enumerable: true, get: function () { return gift_1.defaultGifter; } });
var luckyDraw_1 = require("./types/luckyDraw");
Object.defineProperty(exports, "FFLuckyDrawCriteriaType", { enumerable: true, get: function () { return luckyDraw_1.FFLuckyDrawCriteriaType; } });
Object.defineProperty(exports, "FFLuckyDrawMode", { enumerable: true, get: function () { return luckyDraw_1.FFLuckyDrawMode; } });
Object.defineProperty(exports, "FFLuckyDrawStatus", { enumerable: true, get: function () { return luckyDraw_1.FFLuckyDrawStatus; } });
var news_1 = require("./types/news");
Object.defineProperty(exports, "NewsTag", { enumerable: true, get: function () { return news_1.NewsTag; } });
var notification_1 = require("./types/notification");
Object.defineProperty(exports, "NotificationType", { enumerable: true, get: function () { return notification_1.NotificationType; } });
var platform_1 = require("./types/platform");
Object.defineProperty(exports, "BannerPlatform", { enumerable: true, get: function () { return platform_1.BannerPlatform; } });
Object.defineProperty(exports, "ClientPlatform", { enumerable: true, get: function () { return platform_1.ClientPlatform; } });
Object.defineProperty(exports, "LoginPlatform", { enumerable: true, get: function () { return platform_1.LoginPlatform; } });
Object.defineProperty(exports, "SessionPlatform", { enumerable: true, get: function () { return platform_1.SessionPlatform; } });
Object.defineProperty(exports, "SharingPlatform", { enumerable: true, get: function () { return platform_1.SharingPlatform; } });
Object.defineProperty(exports, "SocialPlatform", { enumerable: true, get: function () { return platform_1.SocialPlatform; } });
Object.defineProperty(exports, "StreamingPlatform", { enumerable: true, get: function () { return platform_1.StreamingPlatform; } });
var playback_1 = require("./types/playback");
Object.defineProperty(exports, "Sort", { enumerable: true, get: function () { return playback_1.Sort; } });
Object.defineProperty(exports, "defaultPlayback", { enumerable: true, get: function () { return playback_1.defaultPlayback; } });
var ranking_1 = require("./types/ranking");
Object.defineProperty(exports, "RankingListKey", { enumerable: true, get: function () { return ranking_1.RankingListKey; } });
Object.defineProperty(exports, "RankingTimeScope", { enumerable: true, get: function () { return ranking_1.RankingTimeScope; } });
Object.defineProperty(exports, "defaultRankingCards", { enumerable: true, get: function () { return ranking_1.defaultRankingCards; } });
var report_1 = require("./types/report");
Object.defineProperty(exports, "Reason", { enumerable: true, get: function () { return report_1.Reason; } });
Object.defineProperty(exports, "Type", { enumerable: true, get: function () { return report_1.Type; } });
var search_1 = require("./types/search");
Object.defineProperty(exports, "SearchType", { enumerable: true, get: function () { return search_1.SearchType; } });
var sentry_1 = require("./types/sentry");
Object.defineProperty(exports, "SentryDeviceDSN", { enumerable: true, get: function () { return sentry_1.SentryDeviceDSN; } });
var stream_1 = require("./types/stream");
Object.defineProperty(exports, "FBPrivacy", { enumerable: true, get: function () { return stream_1.FBPrivacy; } });
Object.defineProperty(exports, "defaultLuckyDrawInfo", { enumerable: true, get: function () { return stream_1.defaultLuckyDrawInfo; } });
var streamerProgram_1 = require("./types/streamerProgram");
Object.defineProperty(exports, "StreamerProgramPayoutStatus", { enumerable: true, get: function () { return streamerProgram_1.StreamerProgramPayoutStatus; } });
Object.defineProperty(exports, "StreamerProgramPayoutWithdrawStatus", { enumerable: true, get: function () { return streamerProgram_1.StreamerProgramPayoutWithdrawStatus; } });
Object.defineProperty(exports, "StreamerProgramRecordOffset", { enumerable: true, get: function () { return streamerProgram_1.StreamerProgramRecordOffset; } });
Object.defineProperty(exports, "StreamerProgramWithdrawType", { enumerable: true, get: function () { return streamerProgram_1.StreamerProgramWithdrawType; } });
Object.defineProperty(exports, "defaultStreamerProgramStats", { enumerable: true, get: function () { return streamerProgram_1.defaultStreamerProgramStats; } });
var streamProgram_1 = require("./types/streamProgram");
Object.defineProperty(exports, "GroupTier", { enumerable: true, get: function () { return streamProgram_1.GroupTier; } });
Object.defineProperty(exports, "ProgramLevel", { enumerable: true, get: function () { return streamProgram_1.ProgramLevel; } });
var tabs_1 = require("./types/tabs");
Object.defineProperty(exports, "TabsScrollPostion", { enumerable: true, get: function () { return tabs_1.TabsScrollPostion; } });
var tasks_1 = require("./types/tasks");
Object.defineProperty(exports, "DailyTaskReward", { enumerable: true, get: function () { return tasks_1.DailyTaskReward; } });
Object.defineProperty(exports, "DailyTaskStatus", { enumerable: true, get: function () { return tasks_1.DailyTaskStatus; } });
Object.defineProperty(exports, "DailyTaskType", { enumerable: true, get: function () { return tasks_1.DailyTaskType; } });
Object.defineProperty(exports, "TLEClaimQueryType", { enumerable: true, get: function () { return tasks_1.TLEClaimQueryType; } });
Object.defineProperty(exports, "TLEEventScope", { enumerable: true, get: function () { return tasks_1.TLEEventScope; } });
Object.defineProperty(exports, "TLEEventType", { enumerable: true, get: function () { return tasks_1.TLEEventType; } });
Object.defineProperty(exports, "TLEPrizeType", { enumerable: true, get: function () { return tasks_1.TLEPrizeType; } });
Object.defineProperty(exports, "TLEQueryType", { enumerable: true, get: function () { return tasks_1.TLEQueryType; } });
Object.defineProperty(exports, "TLERewardType", { enumerable: true, get: function () { return tasks_1.TLERewardType; } });
Object.defineProperty(exports, "TLEStatus", { enumerable: true, get: function () { return tasks_1.TLEStatus; } });
Object.defineProperty(exports, "defaultDailyTask", { enumerable: true, get: function () { return tasks_1.defaultDailyTask; } });
Object.defineProperty(exports, "defaultTimeLimitedTask", { enumerable: true, get: function () { return tasks_1.defaultTimeLimitedTask; } });
var user_1 = require("./types/user");
Object.defineProperty(exports, "BanningSource", { enumerable: true, get: function () { return user_1.BanningSource; } });
Object.defineProperty(exports, "ModerateContent", { enumerable: true, get: function () { return user_1.ModerateContent; } });
Object.defineProperty(exports, "UserGender", { enumerable: true, get: function () { return user_1.UserGender; } });
var util_1 = require("./types/util");
Object.defineProperty(exports, "ApiErrorCode", { enumerable: true, get: function () { return util_1.ApiErrorCode; } });
Object.defineProperty(exports, "FFBindingResult", { enumerable: true, get: function () { return util_1.FFBindingResult; } });
Object.defineProperty(exports, "FileType", { enumerable: true, get: function () { return util_1.FileType; } });
Object.defineProperty(exports, "defaultServerConfig", { enumerable: true, get: function () { return util_1.defaultServerConfig; } });
var video_1 = require("./types/video");
Object.defineProperty(exports, "VideoFilterType", { enumerable: true, get: function () { return video_1.VideoFilterType; } });
Object.defineProperty(exports, "VideoFormat", { enumerable: true, get: function () { return video_1.VideoFormat; } });
Object.defineProperty(exports, "VideoType", { enumerable: true, get: function () { return video_1.VideoType; } });
var videoPlayer_1 = require("./types/videoPlayer");
Object.defineProperty(exports, "PlayerError", { enumerable: true, get: function () { return videoPlayer_1.PlayerError; } });
const RestAPI_1 = __importDefault(require("./RestAPI"));
exports.RestAPI = RestAPI_1.default;
const ChatClient_1 = __importDefault(require("./ChatClient"));
exports.ChatClient = ChatClient_1.default;
//# sourceMappingURL=index.js.map